# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a63ddcd5502a94612867ed8420fb1e8ed0b8ecbd2f581784781070af7c669fe94d8b8fce1f1e965fc0470299a800360943bb1824fb1d6b908c1f761d63adfc

test:
  secret_key_base: ad3a306f853df96f85ad92f9ba2ea4232fcebd322f4b2eefcbe1aa761f820a46bc3c1e78034f0c9e00299b62807840c5996b8ac1e8c9d54545ccda420db04b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
